# This configuration file is for the **development** setup.
# For a production example please refer to getredash/setup repository on GitHub.
version: "2.2"
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_frontend_build: "true" # set to empty string to build
  volumes:
    - .:/app
  env_file:
    - .env
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
  REDASH_GUNICORN_TIMEOUT: 60
  # Set secret keys in the .env file
services:
  server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      # - "5678:5678"
    # expose:
    #   - 5000
    #   - 5678
    restart: always
    <<: *redash-environment
    environment:
      PYTHONUNBUFFERED: 0
    networks:
      - app-network
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    restart: always
    <<: *redash-environment
    networks:
      - app-network
  worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - server
    <<: *redash-environment
    environment:
      PYTHONUNBUFFERED: 0
    restart: always
    networks:
      - app-network
  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5-alpine
    ports:
      - "15432:5432"
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: always
    volumes:
      - redash-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - app-network
  email:
    image: maildev/maildev
    ports:
      - "1080:80"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: nginx/ # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 5432:5432
    depends_on:
      - server
      - postgres
    restart: always
    networks:
      - app-network

volumes:
  redash-data:


networks:
  app-network:
    driver: bridge
